import streamlit as st
import pandas as pd
import plotly.express as px
import os
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image

# ==========================================
# 1. PAGE CONFIGURATION & HEADER
# ==========================================
st.set_page_config(page_title="PlantVillage FL Monitor", page_icon="🌱", layout="wide")

st.markdown("""
    <div style='background-color: #2e7d32; padding: 20px; border-radius: 10px; margin-bottom: 25px;'>
        <h1 style='color: white; margin: 0;'>🌱 PlantVillage MLOps Portal</h1>
        <p style='color: #e8f5e9; margin: 0;'>Federated Learning Model Monitoring & Live Inference Dashboard</p>
    </div>
    """, unsafe_allow_html=True)

# ==========================================
# 2. METRICS DASHBOARD
# ==========================================
metrics_file = "outputs/logs/federated_metrics.csv"

if os.path.exists(metrics_file):
    df = pd.read_csv(metrics_file)
    col1, col2, col3 = st.columns(3)
    final_acc = df['accuracy'].iloc[-1]
    initial_acc = df['accuracy'].iloc[0]
    
    col1.metric("Final Accuracy", f"{final_acc*100:.2f}%", f"{(final_acc - initial_acc)*100:.2f}%")
    col2.metric("Federated Rounds", len(df))
    col3.metric("System Status", "Healthy", delta_color="normal")

    st.subheader("Convergence Analysis")
    fig = px.line(df, x='round', y='accuracy', title='Global Model Accuracy (Interactive)',
                 markers=True, template="plotly_white", color_discrete_sequence=['#2e7d32'])
    fig.update_layout(xaxis_title="Communication Round", yaxis_title="Accuracy (0-1)")
    st.plotly_chart(fig, use_container_width=True)

    with st.expander("📂 View Detailed Round Metrics"):
        st.table(df)
else:
    st.warning(f"Awaiting metrics file at `{metrics_file}`...")

st.markdown("---")

# ==========================================
# 3. EXACT MODEL ARCHITECTURE
# ==========================================
class PlantVillageModel(nn.Module):
    def __init__(self, num_classes=38):
        super().__init__()
        self.base_model = models.mobilenet_v2(weights=None)
        self.base_model.classifier[1] = nn.Linear(1280, num_classes)
        
    def forward(self, x): 
        return self.base_model(x)

# ==========================================
# 4. PLANTVILLAGE CLASS MAPPING
# ==========================================
# Alphabetical sorting exactly as generated by PyTorch ImageFolder
CLASS_NAMES = [
    "Apple - Apple Scab", "Apple - Black Rot", "Apple - Cedar Apple Rust", "Apple - Healthy",
    "Blueberry - Healthy",
    "Cherry - Powdery Mildew", "Cherry - Healthy",
    "Corn - Cercospora Leaf Spot", "Corn - Common Rust", "Corn - Northern Leaf Blight", "Corn - Healthy",
    "Grape - Black Rot", "Grape - Esca (Black Measles)", "Grape - Leaf Blight", "Grape - Healthy",
    "Orange - Citrus Greening",
    "Peach - Bacterial Spot", "Peach - Healthy",
    "Pepper (Bell) - Bacterial Spot", "Pepper (Bell) - Healthy",
    "Potato - Early Blight", "Potato - Late Blight", "Potato - Healthy",
    "Raspberry - Healthy",
    "Soybean - Healthy",
    "Squash - Powdery Mildew",
    "Strawberry - Leaf Scorch", "Strawberry - Healthy",
    "Tomato - Bacterial Spot", "Tomato - Early Blight", "Tomato - Late Blight", "Tomato - Leaf Mold",
    "Tomato - Septoria Leaf Spot", "Tomato - Spider Mites", "Tomato - Target Spot",
    "Tomato - Yellow Leaf Curl Virus", "Tomato - Mosaic Virus", "Tomato - Healthy"
]

# ==========================================
# 5. LIVE INFERENCE ENGINE
# ==========================================
st.subheader("🔬 Live Image Inference Engine")

MODEL_PATH = "outputs/models/global_plant_model.pth"

@st.cache_resource
def load_pytorch_model(path):
    if not os.path.exists(path):
        return None
    try:
        model = PlantVillageModel(num_classes=38) 
        state_dict = torch.load(path, map_location=torch.device('cpu'))
        model.load_state_dict(state_dict, strict=True)
        model.eval()
        return model
    except Exception as e:
        st.error(f"Error loading model framework: {e}")
        return None

model = load_pytorch_model(MODEL_PATH)

if model is None:
    st.error(f"⚠️ Model file not found at `{MODEL_PATH}`. Please ensure your `outputs` folder is inside your deployment directory.")
else:
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    uploaded_file = st.file_uploader("Upload a plant leaf image (JPG, JPEG, PNG)...", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        image = Image.open(uploaded_file).convert("RGB")
        
        col_img, col_pred = st.columns([1, 1])
        
        with col_img:
            st.image(image, caption="Uploaded Leaf Image", use_container_width=True)
            
        with col_pred:
            with st.spinner("Analyzing image..."):
                tensor = transform(image).unsqueeze(0)
                
                with torch.no_grad():
                    outputs = model(tensor)
                    probabilities = torch.nn.functional.softmax(outputs[0], dim=0)
                    confidence, predicted_class = torch.max(probabilities, 0)
                
                conf_score = confidence.item() * 100
                pred_idx = predicted_class.item()
                
                # Fetch human-readable name from the list
                human_readable_class = CLASS_NAMES[pred_idx]
                
                st.success("### Analysis Complete!")
                
                st.metric(label="Predicted Diagnosis", value=human_readable_class)
                st.metric(label="Confidence Score", value=f"{conf_score:.2f}%")
                
                # Dynamic color for progress bar based on confidence
                if conf_score > 85:
                    st.progress(int(conf_score))
                else:
                    st.warning("⚠️ Low confidence prediction. Ensure the image is clear and contains a single plant leaf.")
                    st.progress(int(conf_score))